version: '3.8'

services:
  # MQTT Broker (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./dis/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - iot-network

  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped
    networks:
      - iot-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - iot-network

  # Data Ingestion Service
  data-ingestion-service:
    build:
      context: ./dis
      dockerfile: Dockerfile
    container_name: data-ingestion-service
    depends_on:
      - mqtt-broker
      - clickhouse
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_BROKER_PORT: 1883
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    restart: unless-stopped
    networks:
      - iot-network

  # API Service
  api-service:
    build:
      context: ./apis
      dockerfile: Dockerfile
    container_name: api-service
    depends_on:
      - mqtt-broker
      - clickhouse
      - postgres
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD:
      CLICKHOUSE_DATABASE: iot_monitoring
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: iot_monitoring
    restart: unless-stopped
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  clickhouse-data:
  postgres-data:
